
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPT = 8;
  public static final int CONCATENACION = 2;
  public static final int DECIMAL = 23;
  public static final int LEXEMARECONOCER = 17;
  public static final int POSITIVA = 5;
  public static final int UNAOCERO = 6;
  public static final int ID = 21;
  public static final int COMILLAS = 9;
  public static final int PORCENTAJE = 14;
  public static final int CARACTER = 18;
  public static final int LLAVEIZQ = 12;
  public static final int COMA = 11;
  public static final int ASIGNACION = 15;
  public static final int DEFINICIONCONJUNTO = 25;
  public static final int LLAVEDER = 13;
  public static final int EOF = 0;
  public static final int KLEEN = 4;
  public static final int CONJ = 24;
  public static final int COMILLA = 10;
  public static final int DEFINICIONCONJUNTOCOMAS = 26;
  public static final int DISYUNCION = 3;
  public static final int ESPECIAL = 19;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 20;
  public static final int LEXEMA = 16;
  public static final int ENTERO = 22;
  public static final int PTCOMA = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONCATENACION",
  "DISYUNCION",
  "KLEEN",
  "POSITIVA",
  "UNAOCERO",
  "PTCOMA",
  "DOSPT",
  "COMILLAS",
  "COMILLA",
  "COMA",
  "LLAVEIZQ",
  "LLAVEDER",
  "PORCENTAJE",
  "ASIGNACION",
  "LEXEMA",
  "LEXEMARECONOCER",
  "CARACTER",
  "ESPECIAL",
  "IDENTIFICADOR",
  "ID",
  "ENTERO",
  "DECIMAL",
  "CONJ",
  "DEFINICIONCONJUNTO",
  "DEFINICIONCONJUNTOCOMAS"
  };
}

